config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations'
  }

  devise_scope :user do
    get 'users/new_address_preset', to: 'users/registrations#new_address_preset'
    post 'users/create_address_preset', to: 'users/registrations#create_address_preset'
  end

  root to: "items#index"
  resources :tags, only: [:index]
  resources :items do
    resources :transactions, only: [:index, :new, :create]
    resources :comments, only: :create 
    member do
      get :purchase_confirm
      post :purchase
    end
    collection do
      get 'search'
    end
  end
  resources :cards, only: [:index, :new, :create, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  # <<バリデーション>>

  # 値が入っているか検証
  with_options presence: true do
    validates :images
    validates :name
    validates :info
    validates :price
  end

  # 金額が半角であるか検証
  validates :price, numericality: { with: /\A[0-9]+\z/, message: 'Half-width number' }

  # 金額の範囲
  validates_inclusion_of :price, in: 300..9_999_999, message: 'Out of setting range'

  # <<アクティブハッシュの設定関連>>
  belongs_to_active_hash :category
  belongs_to_active_hash :sales_status
  belongs_to_active_hash :shipping_fee_status
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :scheduled_delivery

  # <<アクティブストレージの設定関連>>
  has_many_attached :images
  validates :images, length: { minimum: 1, maximum: 5, message: "は1枚以上5枚以下にしてください" }
  # <<アソシエーション>>
  belongs_to :user
  has_many :comments
  has_one :item_transaction
  has_many :item_tag_relations, dependent: :destroy
  has_many :tags, through: :item_tag_relations
end

app/models/item_form.rb
class ItemForm
  include ActiveModel::Model
  include ActiveModel::Attributes
  ## ItemFormクラスのオブジェクトがitemモデルの属性を扱えるようにする
  attribute :name,  :string
  attribute :info,  :string
  attribute :category_id, :big_integer
  attribute :sales_status_id, :big_integer
  attribute :shipping_fee_status_id, :big_integer
  attribute :prefecture_id, :big_integer
  attribute :scheduled_delivery_id, :big_integer
  attribute :price, :integer
  attribute :images, :binary
  attribute :user_id, :big_integer
  attribute :tag_name, :string
  attribute :id, :integer
  attribute :created_at, :datetime
  attribute :updated_at, :datetime
  # <<バリデーション（ほぼitem.rbの流用）>>

  # 値が入っているか検証
  with_options presence: true do
    validates :images
    validates :name
    validates :info
    validates :price

  end

  # 金額が半角であるか検証
  validates :price, numericality: { message: 'Half-width number' }

  # 金額の範囲
  validates_inclusion_of :price, in: 300..9_999_999, message: 'Out of setting range'

  # 選択関係で「---」のままになっていないか検証
  with_options numericality: { other_than: 0, message: 'Select' } do
    validates :category_id
    validates :sales_status_id
    validates :shipping_fee_status_id
    validates :prefecture_id
    validates :scheduled_delivery_id
  end

  def save
    item = Item.new(
      name: name,
      info: info,
      price: price,
      category_id: category_id,
      sales_status_id: sales_status_id,
      shipping_fee_status_id: shipping_fee_status_id,
      prefecture_id: prefecture_id,
      scheduled_delivery_id: scheduled_delivery_id,
      user_id: user_id,
      images: images)

    if self.tag_name.present?
      ## 同じタグが作成されることを防ぐため、first_or_initializeで既に存在しているかチェックする
      tag = Tag.where(name: self.tag_name).first_or_initialize
      item.tags << tag
    end
    item.save

  end


  def update(params, item)
    ## paramsからtag_nameを除外し、除外したものを変数tag_nameに入れる
    tag_name = params.delete(:tag_name)
    ## tag_nameが空ではない場合はタグを作る。first_or_initializeで重複がないかを確認しておく。
    ## ※先にtagを定義しておかないとrescue内でtagが使えない
    tag = Tag.where(name: tag_name).first_or_initialize if tag_name.present?
    ActiveRecord::Base.transaction do
      tag.save if tag_name.present?
      ## updateに!をつけると失敗したらrescueへ
      item.update!(params)
      ## itemから一旦タグを外す。
      item.item_tag_relations.destroy_all
      ## tag_nameがある場合はタグを付け直す。tag_nameがない場合はタグが0個になる
      ## ※タグがバリデーションに引っかかるとここでrescueへ行く
      item.tags << tag if tag_name.present?
      ## 成功であることを呼び出し元であるコントローラに伝えて終了
      return true
    end
    rescue => e
      ## なんらかのバリデーションに引っかかったとき、フォームオブジェクトへエラーメッセージを足していく
      ## itemのnameとtagのnameでエラーメッセージのキーが重複するため、tagはtag_nameとしておく
      tag.errors.messages[:tag_name] = tag.errors.messages.delete(:name) if tag&.errors&.messages&.present?
      ## itemのエラーメッセージをitem_formオブジェクトのエラーメッセージに追加していく
      item.errors&.messages&.each do |key, message|
        self.errors.add(key, message.first)
      end
      ## tagのエラーメッセージをitem_formオブジェクトのエラーメッセージに追加していく
      tag&.errors&.messages&.each do |key, message|
        self.errors.add(key, message.first)
      end
      ## 失敗したことを呼び出し元であるコントローラに伝えて終了
      return false
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :select_item, only: [:show, :edit, :update, :destroy, :purchase_confirm, :purchase]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :purchase_confirm, :purchase]
  before_action :sold_item, only: [:purchase_confirm, :purchase]
  before_action :current_user_has_not_card, only: [:purchase_confirm, :purchase]
  before_action :set_item_form, only: [:edit, :update]
  def index
    @items = Item.all.order(created_at: :desc)
  end

  def new
    @item_form = ItemForm.new
  end
  
  def create
    @item_form = ItemForm.new(item_form_params)
    # バリデーションで問題があれば、保存はされず「商品出品画面」を再描画
    if @item_form.valid?
      @item_form.save
      return redirect_to root_path
    end
    # アクションのnewをコールすると、エラーメッセージが入った@itemが上書きされてしまうので注意
    render 'new'
  end

  def search
    if params[:q]&.dig(:name)  ## if params[:q] && params[:q][:name]と同じようなもの
      ## squishメソッドで無駄なスペースを圧縮する
      ## 例えば "hoge         fuga    foo  bar"は"hoge fuga foo bar"になる
      squished_keywords = params[:q][:name].squish
      ## 半角スペースを区切り文字として配列にしてparamsに入れる
      ## 例えば文字列"hoge fuga foo bar"は配列[hoge, fuga, foo, bar]になる
      params[:q][:name_cont_any] = squished_keywords.split(" ")
    end
    @q = Item.ransack(params[:q])
    @items = @q.result
  end
  
  def purchase
    ## 購入履歴オブジェクトを定義
    item_transaction = ItemTransaction.new(item_id: @item.id, user_id: current_user.id)

    ## 購入履歴オブジェクトに紐づく配送先オブジェクトを定義
    @address = item_transaction.build_address(address_params)
    if @address.valid?
      ## 配送先を保存できるとき
      Payjp.api_key = ENV['PAYJP_SK']      
      Payjp::Charge.create(
        amount: @item.price,
        customer: current_user.card.customer_token,  ## 顧客のトークンを渡す
        currency: 'jpy'
      )

      @address.save
      redirect_to root_path
    else
      ## 配送先を保存できないとき
      redirect_to purchase_confirm_item_path(@item)
    end
  end

  def purchase_confirm
    @address = Address.new
  end

  def show
    @comments = @item.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    return redirect_to root_path if current_user.id != @item.user.id
  end

  def update
    render 'edit' unless current_user.id == @item.user.id
    @item_form = ItemForm.new(item_form_params)
    if @item_form.update(item_form_params, @item)
      return redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy if current_user.id == @item.user.id
    redirect_to root_path
  end

  private

  def item_form_params
    ## require(:item) → require(:item_form)
    params.require(:item_form).permit(
      :name,
      :info,
      :category_id,
      :tag_name,
      :sales_status_id,
      :shipping_fee_status_id,
      :prefecture_id,
      :scheduled_delivery_id,
      :price,
      {images: []}
    ).merge(user_id: current_user.id)
  end

  def select_item
    @item = Item.find(params[:id])
  end

  def address_params
    params.permit(
      :postal_code,
      :prefecture,
      :city,
      :addresses,
      :building,
      :phone_number
    )
  end

  def set_item_form
    item_attributes = @item.attributes
    @item_form = ItemForm.new(item_attributes)
  end
  
  def sold_item
    redirect_to item_path(@item), alert: "売り切れの商品です" if @item.item_transaction.present?
  end
  
  def current_user_has_not_card
    redirect_to new_card_path, alert: "クレジットカードが登録されていません" unless current_user.card.present?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<% breadcrumb :edit_item, @item %>
<%= render partial: 'form', locals: {url: item_path, method: :patch} %>

app/views/items/index.html.erb
<% breadcrumb :root %>
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# //画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "pict-reason-01.jpg", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "pict-reason-02.jpg", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "pict-reason-03.jpg", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          最大3%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  <%# //FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# //画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "icon-01.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "icon-03.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "icon-04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# //FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規投稿商品', new_item_path, class: "subtitle" %>
    <ul class='item-lists'>
      <% if @items[0] != nil%>
      <% @items.each do |item|%>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.images[0], class: "item-img" %>
          <%# sold outの表示 %>
          <% if item.item_transaction != nil %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star-icon.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <% end %>
      <%# 商品がない場合のダミー %>
      <% if @items.length == 0%>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star-icon.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <%# //商品がない場合のダミー %>
    </ul>
  </div>
  <%# //商品一覧 %>
</div>
<a href="/items/new">
  <div class='purchase-btn'>
    <span class='purchase-btn-text'>出品する</span>
    <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </div>
</a>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<% breadcrumb :new_item %>
<%= render partial: 'form', locals: {url: items_path, method: :post} %>

app/views/items/purchase_confirm.html.erb
<% breadcrumb :purchase_with_card, @item %>
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @item.images[0], class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @item.name %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= @item.price %></p>
          <p class='item-price-sub-text'>（税込）送料込み</p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= @item.price %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with url: purchase_item_path, id: 'item-purchase-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%= render 'shared/error_messages', model: @address %>
    <%# /カード情報の入力 %>
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'postal_code', class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'city', class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'addresses', class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field 'building', class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'phone_number', class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/items/search.html.erb
<%= render "shared/header" %>
<div class='main' id="detailed-search-wrapper">

  <%= search_form_for @q, url: search_items_path, html: {id: "detailed-search-form"} do |f| %>

    <div class="search-field">
      <%= f.label :name, '商品名' %>
      <br>
      <%= f.text_field :name_or, placeholder: '商品名', value: params[:q]&.dig(:name) %>
    </div>

    <div class="search-field">
      <%= f.label :user_nickname_cont, '出品者名' %>
      <br>
      <%= f.text_field :user_nickname_cont, placeholder: '出品者名' %>
    </div>

    <div class="search-field">
      <%= f.label :category_id_in, 'カテゴリ' %>
      <br>
      <%= f.collection_check_boxes :category_id_in, Category.all, :id, :name, {include_blank: "---"} %>
    </div>

    <div class="search-field">
      <%= f.label :sales_status_id_eq, '状態' %>
      <br>
      <%= f.collection_select :sales_status_id_eq, SalesStatus.all, :id, :example, {include_blank: "---"} %>
    </div>

    <div class="search-field">
      <%= f.label :shipping_fee_status_id_eq, '送料負担' %>
      <br>
      <%= f.collection_select :shipping_fee_status_id_eq, ShippingFeeStatus.all, :id, :fee, {include_blank: "---"} %>
    </div>

    <div class="search-field">
      <%= f.label :scheduled_delivery_id_eq, '発送日目安' %>
      <br>
      <%= f.collection_select :scheduled_delivery_id_eq, ScheduledDelivery.all, :id, :date, {include_blank: "---"} %>
    </div>

    <div class="search-field">
      <%= f.label :prefecture_id_eq, '発送元地域' %>
      <br>
      <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, {include_blank: "---"} %>
    </div>

    <div class="search-field">
      <%= f.label :price_gteq, '価格'%>
      <br>
      <%= f.number_field :price_gteq %>
      <br>
      ～
      <br>
      <%= f.number_field :price_lteq %>
    </div>
    <%= f.submit '検索' %>
  <% end %>

  <%# 商品一覧 %>
  <div class='item-contents' id="detailed-search-result-wrapper">
    <%= link_to '新規投稿商品', new_item_path, class: "subtitle" %>
    <ul class='item-lists' id="detailed-search-result">
      <% if @items[0] != nil%>
        <% @items.each do |item|%>
          <li class='list'>
            <%= link_to item_path(item.id) do %>
              <div class='item-img-content'>
                <%= image_tag item.images[0], class: "item-img" %>
                <%# sold outの表示 %>
                <% if item.item_transaction != nil %>
                <div class='sold-out'>
                  <span>Sold Out!!</span>
                </div>
                <% end %>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= item.name %>
                </h3>
                <div class='item-price'>
                  <span><%= item.price %>円<br>(税込み)</span>
                  <div class='star-btn'>
                    <%= image_tag "star-icon.png", class:"star-icon" %>
                    <span class='star-count'>0</span>
                  </div>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      <% end %>

    </ul>
  </div>
  <%# //商品一覧 %>
</div>
<a href="/items/new">
  <div class='purchase-btn'>
    <span class='purchase-btn-text'>出品する</span>
    <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </div>
</a>

<%= render "shared/footer" %>

app/views/items/show.html.erb
<% breadcrumb :show_item, @item %>
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @item.images[0] ,class:"item-box-img" %>
      <% if @item.item_transaction != nil %>
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div>
      <% end %>
    </div>
    <div id='item-mini-images' style="display:flex;">
      <% @item.images[1..-1].each do |image|%>
        <%= image_tag image.variant(resize:'300x300')%>
      <%end%>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @item.price %>
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>
    </div>
    <% if user_signed_in? && @item.item_transaction == nil%>
      <% if current_user.id == @item.user_id %>
        <%= link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
        <p class='or-text'>or</p>
        <%= link_to '削除', item_path(@item.id), method: :delete, class:'item-destroy' %>
      <% else %>
        <%= link_to '購入画面に進む（新しくカードを登録する）', item_transactions_path(item_id: @item.id) ,class:"item-red-btn"%>
        <%= link_to '購入画面に進む（カード登録済み）', purchase_confirm_item_path(item_id: @item.id) ,class:"item-red-btn"%>
      <% end %>
    <% end %>
    <div class="item-explain-box">
      <span><%= @item.info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">タグ</th>
          <td class="detail-value"><%= @item.tags&.first&.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.sales_status.example %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.shipping_fee_status.fee %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.scheduled_delivery.date %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star-icon.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>
  <div class="comment-box" id="comment-box">
    <div id="comments">
      <% @item.comments.each do |comment| %>
        <div class="comment">
          <div class="user-info"><%= comment.user.nickname %></div>
          <p><%= comment.content%></p>
        </div>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <%= form_with model: [@item, @comment], id: "comment_form" do |f| %>
        <%= f.text_area :content , class: "comment-text"%>
        <p class="comment-warn" >
          相手のことを考え丁寧なコメントを心がけましょう。
          <br>
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        </p>
        <%# f.submitだとdo使えないので、buttonで代用。 %>
        <%= f.button type: 'submit', class: "comment-btn" do %>
          <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
          <span>コメントする<span>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class='another-item'><%= @item.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>